/*---------------------------------------------------------------------------*\

  rade_text.c

  Self-contained RADE EOO text encoder/decoder.

  Encodes a callsign (max 8 chars) into LDPC(112,56) coded QPSK symbols
  for transmission in the RADE End-of-Over frame.  Decodes the same on RX.

  Wire-compatible with freedv-gui's rade_text.  No codec2 dependency —
  all LDPC, interleaver, and phi0 code is embedded.

  Original rade_text by Mooneer Salem (freedv-gui, Dec 2024).
  LDPC codec by Matthew C. Valenti / David Rowe (codec2).
  GP interleaver by David Rowe (codec2).
  Ported to radae_nopy by Alain De Carolis, 2026.

\*---------------------------------------------------------------------------*/

/*
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  - Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  - Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "rade_text.h"

#include <assert.h>
#include <ctype.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*---------------------------------------------------------------------------*\
                          LDPC CODE: HRA_56_56
  Rate 1/2, 56 info bits + 56 parity bits = 112 coded bits.
  Generated by ldpc_gen_c_h_file.m (codec2).
\*---------------------------------------------------------------------------*/

#define LDPC_CODELENGTH         112
#define LDPC_NPARITY            56
#define LDPC_NDATA              56
#define LDPC_MAX_ROW_WEIGHT     3
#define LDPC_MAX_COL_WEIGHT     3
#define LDPC_MAX_ITER           100

static const uint16_t HRA_56_56_H_rows[] = {
    4,  33, 22, 2,  7,  12, 15, 41, 6,  2,  8,  4,  1,  7,  20, 10, 2,  1,  28,
    7,  3,  25, 18, 19, 17, 15, 8,  13, 9,  12, 39, 6,  17, 32, 3,  6,  10, 18,
    4,  34, 1,  14, 9,  5,  15, 12, 5,  35, 5,  17, 16, 36, 20, 9,  34, 33, 14,
    46, 39, 27, 43, 22, 19, 45, 16, 23, 31, 52, 3,  8,  51, 13, 31, 11, 31, 36,
    11, 28, 30, 21, 38, 26, 42, 29, 23, 33, 45, 19, 28, 40, 10, 23, 41, 25, 29,
    36, 29, 49, 38, 11, 30, 42, 16, 37, 49, 35, 18, 47, 24, 25, 54, 34, 41, 55,
    47, 44, 56, 46, 20, 55, 21, 40, 37, 53, 13, 32, 52, 22, 32, 24, 44, 42, 49,
    38, 48, 24, 56, 48, 50, 39, 26, 50, 54, 26, 37, 56, 14, 27, 46, 44, 45, 43,
    53, 52, 40, 21, 51, 47, 30, 50, 51, 43, 27, 54, 53, 48, 55, 35
};

static const uint16_t HRA_56_56_H_cols[] = {
    13, 4,  13, 1,  44, 9,  5,  11, 29, 16, 18, 6,  13, 1,  7,  9,  25, 23, 7,
    7,  9,  3,  10, 18, 22, 26, 4,  19, 28, 23, 11, 14, 2,  40, 48, 20, 11, 22,
    3,  10, 1,  20, 5,  4,  8,  2,  3,  23, 21, 27, 15, 12, 12, 31, 2,  5,  18,
    10, 21, 12, 47, 32, 14, 14, 43, 35, 21, 30, 16, 35, 26, 47, 33, 38, 24, 15,
    24, 6,  29, 24, 38, 29, 36, 22, 39, 45, 17, 17, 30, 55, 50, 40, 33, 25, 28,
    34, 8,  27, 40, 19, 31, 6,  46, 26, 42, 30, 45, 15, 41, 52, 8,  25, 41, 17,
    35, 39, 49, 36, 20, 27, 54, 37, 44, 46, 28, 42, 45, 51, 50, 51, 32, 53, 44,
    16, 36, 53, 54, 32, 51, 33, 41, 47, 19, 34, 56, 56, 56, 52, 48, 43, 31, 43,
    37, 46, 50, 38, 39, 37, 52, 54, 49, 48, 49, 42, 53, 55, 55, 34
};

/*---------------------------------------------------------------------------*\
                         COMPLEX NUMBER (local)
\*---------------------------------------------------------------------------*/

typedef struct { float real; float imag; } rt_comp;

/*---------------------------------------------------------------------------*\
                          QPSK CONSTELLATION
  Same mapping as codec2 — used by symbols_to_llrs.
\*---------------------------------------------------------------------------*/

#define QPSK_M   4
#define QPSK_BPS 2

static const rt_comp S_matrix[QPSK_M] = {
    {1.0f, 0.0f}, {0.0f, 1.0f}, {0.0f, -1.0f}, {-1.0f, 0.0f}
};

/*---------------------------------------------------------------------------*\
                            PHI0 FUNCTION
  Approximation of phi0(x) = log((e^x + 1)/(e^x - 1)) used by SumProduct.
  From codec2 gen_phi0 — lookup table for embedded targets.
\*---------------------------------------------------------------------------*/

#define SI16(f) ((int32_t)((f) * (1 << 16)))

static float phi0(float xf) {
    int32_t x = SI16(xf);

    if (x >= SI16(10.0f))
        return 0.0f;

    if (x >= SI16(5.0f)) {
        int i = 19 - (x >> 15);
        static const float tbl[] = {
            0.000116589f, 0.000192223f, 0.000316923f, 0.000522517f,
            0.000861485f, 0.001420349f, 0.002341760f, 0.003860913f,
            0.006365583f, 0.010495133f
        };
        if (i >= 0 && i < 10) return tbl[i];
        return 0.010495133f;
    }

    if (x >= SI16(1.0f)) {
        int i = 79 - (x >> 12);
        static const float tbl[] = {
            0.013903889f, 0.014800644f, 0.015755242f, 0.016771414f,
            0.017853133f, 0.019004629f, 0.020230403f, 0.021535250f,
            0.022924272f, 0.024402903f, 0.025976926f, 0.027652501f,
            0.029436184f, 0.031334956f, 0.033356250f, 0.035507982f,
            0.037798579f, 0.040237016f, 0.042832850f, 0.045596260f,
            0.048538086f, 0.051669874f, 0.055003924f, 0.058553339f,
            0.062332076f, 0.066355011f, 0.070637993f, 0.075197917f,
            0.080052790f, 0.085221814f, 0.090725463f, 0.096585578f,
            0.102825462f, 0.109469985f, 0.116545700f, 0.124080967f,
            0.132106091f, 0.140653466f, 0.149757747f, 0.159456024f,
            0.169788027f, 0.180796343f, 0.192526667f, 0.205028078f,
            0.218353351f, 0.232559308f, 0.247707218f, 0.263863255f,
            0.281099022f, 0.299492155f, 0.319127030f, 0.340095582f,
            0.362498271f, 0.386445235f, 0.412057648f, 0.439469363f,
            0.468828902f, 0.500301872f, 0.534073947f, 0.570354566f,
            0.609381573f, 0.651427083f, 0.696805010f, 0.745880827f
        };
        if (i >= 0 && i < 64) return tbl[i];
        return 0.745880827f;
    }

    /* x < 1.0 — binary search tree (from codec2 gen_phi0) */
    if (x > SI16(0.007812f)) {
        if (x > SI16(0.088388f)) {
            if (x > SI16(0.250000f)) {
                if (x > SI16(0.500000f)) {
                    return (x > SI16(0.707107f)) ? 0.922449644f : 1.241248638f;
                } else {
                    return (x > SI16(0.353553f)) ? 1.573515241f : 1.912825912f;
                }
            } else {
                if (x > SI16(0.125000f)) {
                    return (x > SI16(0.176777f)) ? 2.255740095f : 2.600476919f;
                } else {
                    return 2.946130351f;
                }
            }
        } else {
            if (x > SI16(0.022097f)) {
                if (x > SI16(0.044194f)) {
                    return (x > SI16(0.062500f)) ? 3.292243417f : 3.638586634f;
                } else {
                    return (x > SI16(0.031250f)) ? 3.985045009f : 4.331560985f;
                }
            } else {
                if (x > SI16(0.011049f)) {
                    return (x > SI16(0.015625f)) ? 4.678105767f : 5.024664952f;
                } else {
                    return 5.371231340f;
                }
            }
        }
    } else {
        if (x > SI16(0.000691f)) {
            if (x > SI16(0.001953f)) {
                if (x > SI16(0.003906f)) {
                    return (x > SI16(0.005524f)) ? 5.717801329f : 6.064373119f;
                } else {
                    return (x > SI16(0.002762f)) ? 6.410945809f : 6.757518949f;
                }
            } else {
                if (x > SI16(0.000977f)) {
                    return (x > SI16(0.001381f)) ? 7.104092314f : 7.450665792f;
                } else {
                    return 7.797239326f;
                }
            }
        } else {
            if (x > SI16(0.000173f)) {
                if (x > SI16(0.000345f)) {
                    return (x > SI16(0.000488f)) ? 8.143812888f : 8.490386464f;
                } else {
                    return (x > SI16(0.000244f)) ? 8.836960047f : 9.183533634f;
                }
            } else {
                if (x > SI16(0.000086f)) {
                    return (x > SI16(0.000122f)) ? 9.530107222f : 9.876680812f;
                } else {
                    return 10.000000000f;
                }
            }
        }
    }
    return 10.0f;
}

/*---------------------------------------------------------------------------*\
                         LDPC ENCODER
  Systematic HRA (accumulate) encoder — from codec2 mpdecode_core.c.
\*---------------------------------------------------------------------------*/

static void ldpc_encode(unsigned char ibits[], unsigned char pbits[]) {
    unsigned int p, i, tmp, par, prev = 0;
    int ind;

    for (p = 0; p < LDPC_NPARITY; p++) {
        par = 0;
        for (i = 0; i < LDPC_MAX_ROW_WEIGHT; i++) {
            ind = HRA_56_56_H_rows[p + i * LDPC_NPARITY];
            if (ind) par = par + ibits[ind - 1];
        }
        tmp = par + prev;
        tmp &= 1;
        prev = tmp;
        pbits[p] = tmp;
    }
}

/*---------------------------------------------------------------------------*\
                        LDPC DECODER (Sum-Product)
  Belief propagation on the Tanner graph.
  From codec2 mpdecode_core.c (Valenti / Rowe).
\*---------------------------------------------------------------------------*/

struct c_sub_node { uint16_t index; uint16_t socket; float message; };
struct c_node     { int degree; struct c_sub_node *subs; };
struct v_sub_node { uint16_t index; uint16_t socket; float message; uint8_t sign; };
struct v_node     { int degree; float initial_value; struct v_sub_node *subs; };

static void init_c_v_nodes(struct c_node *c_nodes, struct v_node *v_nodes,
                           float *input) {
    int i, j, count, c_index, v_index;

    /* H1=1, shift=0 for HRA_56_56:
       NumberRowsHcols(56) != CodeLength(112) → H1=1
       shift = (56+56) - 112 = 0 */

    /* Determine degree of each c-node */
    for (i = 0; i < LDPC_NPARITY; i++) {
        count = 0;
        for (j = 0; j < LDPC_MAX_ROW_WEIGHT; j++) {
            if (HRA_56_56_H_rows[i + j * LDPC_NPARITY] > 0)
                count++;
        }
        /* H1=1, shift=0: first row gets +1, others get +2 */
        c_nodes[i].degree = (i == 0) ? count + 1 : count + 2;
    }

    /* Allocate and populate c-node sub-nodes */
    for (i = 0; i < LDPC_NPARITY; i++) {
        c_nodes[i].subs = (struct c_sub_node *)calloc(c_nodes[i].degree,
                                                       sizeof(struct c_sub_node));
        /* Regular connections from H_rows */
        for (j = 0; j < c_nodes[i].degree - 2; j++)
            c_nodes[i].subs[j].index = HRA_56_56_H_rows[i + j * LDPC_NPARITY] - 1;

        /* Accumulate connections (H1=1, shift=0) */
        j = c_nodes[i].degree - 2;
        if (i == 0) {
            c_nodes[i].subs[j].index = HRA_56_56_H_rows[i + j * LDPC_NPARITY] - 1;
        } else {
            c_nodes[i].subs[j].index = LDPC_NDATA + i - 1;
        }
        j = c_nodes[i].degree - 1;
        c_nodes[i].subs[j].index = LDPC_NDATA + i;
    }

    /* Determine degree of each v-node */
    for (i = 0; i < LDPC_NDATA; i++) {
        count = 0;
        for (j = 0; j < LDPC_MAX_COL_WEIGHT; j++) {
            if (HRA_56_56_H_cols[i + j * LDPC_NPARITY] > 0)
                count++;
        }
        v_nodes[i].degree = count;
    }
    /* Parity v-nodes: degree 2, except last which is degree 1 */
    for (i = LDPC_NDATA; i < LDPC_CODELENGTH; i++) {
        v_nodes[i].degree = (i != LDPC_CODELENGTH - 1) ? 2 : 1;
    }

    /* Set up v-nodes */
    for (i = 0; i < LDPC_CODELENGTH; i++) {
        v_nodes[i].subs = (struct v_sub_node *)calloc(v_nodes[i].degree,
                                                       sizeof(struct v_sub_node));
        v_nodes[i].initial_value = input[i];
        count = 0;

        for (j = 0; j < v_nodes[i].degree; j++) {
            if (i >= LDPC_NDATA) {
                /* Parity v-node: connected to c-nodes via accumulate structure */
                v_nodes[i].subs[j].index = i - LDPC_NDATA + count;
                count++;
            } else {
                v_nodes[i].subs[j].index = HRA_56_56_H_cols[i + j * LDPC_NPARITY] - 1;
            }

            /* Find matching socket in connected c-node */
            for (c_index = 0; c_index < c_nodes[v_nodes[i].subs[j].index].degree; c_index++) {
                if (c_nodes[v_nodes[i].subs[j].index].subs[c_index].index == (uint16_t)i) {
                    v_nodes[i].subs[j].socket = c_index;
                    break;
                }
            }
            v_nodes[i].subs[j].message = phi0(fabsf(input[i]));
            if (input[i] < 0) v_nodes[i].subs[j].sign = 1;
        }
    }

    /* Finish c-node setup: find matching sockets in v-nodes */
    for (i = 0; i < LDPC_NPARITY; i++) {
        for (j = 0; j < c_nodes[i].degree; j++) {
            for (v_index = 0; v_index < v_nodes[c_nodes[i].subs[j].index].degree; v_index++) {
                if (v_nodes[c_nodes[i].subs[j].index].subs[v_index].index == (uint16_t)i) {
                    c_nodes[i].subs[j].socket = v_index;
                    break;
                }
            }
        }
    }
}

static int sum_product(int *parityCheckCount, char DecodedBits[],
                       struct c_node c_nodes[], struct v_node v_nodes[]) {
    int i, j, iter, sign, ssum, result;
    float phi_sum, temp_sum, Qi;

    result = LDPC_MAX_ITER;
    for (iter = 0; iter < LDPC_MAX_ITER; iter++) {
        for (i = 0; i < LDPC_CODELENGTH; i++) DecodedBits[i] = 0;

        /* Update r (check-to-variable messages) */
        ssum = 0;
        for (j = 0; j < LDPC_NPARITY; j++) {
            sign = v_nodes[c_nodes[j].subs[0].index]
                       .subs[c_nodes[j].subs[0].socket].sign;
            phi_sum = v_nodes[c_nodes[j].subs[0].index]
                          .subs[c_nodes[j].subs[0].socket].message;

            for (i = 1; i < c_nodes[j].degree; i++) {
                struct c_sub_node *cp = &c_nodes[j].subs[i];
                struct v_sub_node *vp = &v_nodes[cp->index].subs[cp->socket];
                phi_sum += vp->message;
                sign ^= vp->sign;
            }
            if (sign == 0) ssum++;

            for (i = 0; i < c_nodes[j].degree; i++) {
                struct c_sub_node *cp = &c_nodes[j].subs[i];
                struct v_sub_node *vp = &v_nodes[cp->index].subs[cp->socket];
                if (sign ^ vp->sign)
                    cp->message = -phi0(phi_sum - vp->message);
                else
                    cp->message = phi0(phi_sum - vp->message);
            }
        }

        /* Update q (variable-to-check messages) */
        for (i = 0; i < LDPC_CODELENGTH; i++) {
            Qi = v_nodes[i].initial_value;
            for (j = 0; j < v_nodes[i].degree; j++) {
                struct v_sub_node *vp = &v_nodes[i].subs[j];
                Qi += c_nodes[vp->index].subs[vp->socket].message;
            }
            if (Qi < 0) DecodedBits[i] = 1;

            for (j = 0; j < v_nodes[i].degree; j++) {
                struct v_sub_node *vp = &v_nodes[i].subs[j];
                temp_sum = Qi - c_nodes[vp->index].subs[vp->socket].message;
                vp->message = phi0(fabsf(temp_sum));
                vp->sign = (temp_sum > 0) ? 0 : 1;
            }
        }

        *parityCheckCount = ssum;
        if (ssum == LDPC_NPARITY) { result = iter + 1; break; }
    }
    return result;
}

static int ldpc_decode(uint8_t out_char[], float input[], int *parityCheckCount) {
    int i;
    struct c_node *c_nodes = (struct c_node *)calloc(LDPC_NPARITY, sizeof(struct c_node));
    struct v_node *v_nodes = (struct v_node *)calloc(LDPC_CODELENGTH, sizeof(struct v_node));
    char *decoded = (char *)calloc(LDPC_CODELENGTH, sizeof(char));

    init_c_v_nodes(c_nodes, v_nodes, input);
    int iter = sum_product(parityCheckCount, decoded, c_nodes, v_nodes);

    for (i = 0; i < LDPC_CODELENGTH; i++) out_char[i] = decoded[i];

    free(decoded);
    for (i = 0; i < LDPC_NPARITY; i++) free(c_nodes[i].subs);
    free(c_nodes);
    for (i = 0; i < LDPC_CODELENGTH; i++) free(v_nodes[i].subs);
    free(v_nodes);

    return iter;
}

/*---------------------------------------------------------------------------*\
                       SYMBOLS TO LLR CONVERSION
  Converts received QPSK symbols to log-likelihood ratios for the decoder.
  From codec2 mpdecode_core.c.
\*---------------------------------------------------------------------------*/

#define AJIAN  (-0.24904163195436f)
#define TJIAN  2.50681740420944f

static float max_star0(float d1, float d2) {
    float diff = d2 - d1;
    if (diff > TJIAN)        return d2;
    else if (diff < -TJIAN)  return d1;
    else if (diff > 0)       return d2 + AJIAN * (diff - TJIAN);
    else                     return d1 - AJIAN * (diff + TJIAN);
}

static void symbols_to_llrs(float llr[], rt_comp rx_syms[], float rx_amps[],
                            float EsNo, float mean_amp, int nsyms) {
    int i, j, k, mask;
    float sym_lk[QPSK_M];
    float num[QPSK_BPS], den[QPSK_BPS];

    for (i = 0; i < nsyms; i++) {
        /* Demod2D: compute symbol likelihoods */
        for (j = 0; j < QPSK_M; j++) {
            float Er = rx_syms[i].real / mean_amp - rx_amps[i] * S_matrix[j].real / mean_amp;
            float Ei = rx_syms[i].imag / mean_amp - rx_amps[i] * S_matrix[j].imag / mean_amp;
            sym_lk[j] = -EsNo * (Er * Er + Ei * Ei);
        }

        /* Somap: soft output MAP — symbol likelihoods to bit LLRs */
        for (k = 0; k < QPSK_BPS; k++) {
            num[k] = -1000000.0f;
            den[k] = -1000000.0f;
        }
        for (j = 0; j < QPSK_M; j++) {
            mask = 1 << (QPSK_BPS - 1);
            for (k = 0; k < QPSK_BPS; k++) {
                if (mask & j)
                    num[k] = max_star0(num[k], sym_lk[j]);
                else
                    den[k] = max_star0(den[k], sym_lk[j]);
                mask >>= 1;
            }
        }
        for (k = 0; k < QPSK_BPS; k++)
            llr[QPSK_BPS * i + k] = -(num[k] - den[k]);
    }
}

/*---------------------------------------------------------------------------*\
                       GP INTERLEAVER (N=56, b=37)
  Golden Prime interleaver — from codec2 gp_interleaver.c (David Rowe).
  For HRA_56_56: N=56 QPSK symbols, b=37.
\*---------------------------------------------------------------------------*/

#define GP_N 56
#define GP_B 37

/* Interleave 112 bits (56 QPSK symbols), operating on pairs of bits. */
static void gp_interleave_bits(char out[], const char in[]) {
    char temp[GP_N];
    int i, j;
    for (i = 0; i < GP_N; i++) {
        j = (GP_B * i) % GP_N;
        temp[j] = ((in[i * 2] & 1) << 1) | (in[i * 2 + 1] & 1);
    }
    for (i = 0; i < GP_N; i++) {
        out[i * 2]     = temp[i] >> 1;
        out[i * 2 + 1] = temp[i] & 1;
    }
}

/* Deinterleave complex symbols (56 QPSK symbols). */
static void gp_deinterleave_comp(rt_comp out[], const rt_comp in[]) {
    int i, j;
    for (i = 0; i < GP_N; i++) {
        j = (GP_B * i) % GP_N;
        out[i] = in[j];
    }
}

/*---------------------------------------------------------------------------*\
                         RADE TEXT IMPLEMENTATION
\*---------------------------------------------------------------------------*/

#define RADE_TEXT_MAX_LENGTH 8
#define RADE_TEXT_CRC_LENGTH 1
#define RADE_TEXT_MAX_RAW    (RADE_TEXT_MAX_LENGTH + RADE_TEXT_CRC_LENGTH)

typedef struct {
    on_text_rx_t text_rx_callback;
    void        *callback_state;
    char         tx_text[LDPC_CODELENGTH];
} rade_text_impl_t;

/*
   6-bit character set:
     0:     null
     1-9:   ASCII 38-47  (&'()*+,-./)
     10-19: ASCII '0'-'9'
     20-46: ASCII 'A'-'Z'
     47:    ASCII ' '
*/

static void callsign_to_ota(const char *in, char *out, int maxLen) {
    int o = 0;
    for (int i = 0; i < maxLen && in[i]; i++) {
        char c = in[i];
        if (c >= 38 && c <= 47)       out[o++] = c - 37;
        else if (c >= '0' && c <= '9') out[o++] = c - '0' + 10;
        else if (c >= 'A' && c <= 'Z') out[o++] = c - 'A' + 20;
        else if (c >= 'a' && c <= 'z') out[o++] = toupper(c) - 'A' + 20;
        else if (c == ' ')             out[o++] = 47;
    }
    out[o] = 0;
}

static void ota_to_callsign(const char *in, char *out, int maxLen) {
    int o = 0;
    for (int i = 0; i < maxLen && in[i]; i++) {
        unsigned char c = (unsigned char)in[i];
        if (c >= 1 && c <= 9)        out[o++] = c + 37;
        else if (c >= 10 && c <= 19)  out[o++] = c - 10 + '0';
        else if (c >= 20 && c <= 46)  out[o++] = c - 20 + 'A';
        else if (c == 47)             out[o++] = ' ';
    }
    out[o] = 0;
}

static unsigned char crc8(const char *data, int len) {
    unsigned char generator = 0x1D;
    unsigned char crc = 0x00;
    for (int i = 0; i < len; i++) {
        if (data[i] == 0) break;
        crc ^= (unsigned char)data[i];
        for (int b = 0; b < 8; b++)
            crc = (crc & 0x80) ? (unsigned char)((crc << 1) ^ generator) : (crc << 1);
    }
    return crc;
}

/*---------------------------------------------------------------------------*\
                           PUBLIC API
\*---------------------------------------------------------------------------*/

rade_text_t rade_text_create(void) {
    rade_text_impl_t *impl = (rade_text_impl_t *)calloc(1, sizeof(rade_text_impl_t));
    return (rade_text_t)impl;
}

void rade_text_destroy(rade_text_t ptr) {
    free(ptr);
}

void rade_text_set_rx_callback(rade_text_t ptr, on_text_rx_t fn, void *state) {
    rade_text_impl_t *impl = (rade_text_impl_t *)ptr;
    impl->text_rx_callback = fn;
    impl->callback_state = state;
}

void rade_text_generate_tx_string(rade_text_t ptr, const char *str,
                                  int strlength, float *syms, int symSize) {
    rade_text_impl_t *impl = (rade_text_impl_t *)ptr;

    /* Build raw payload: [CRC-8][6-bit OTA chars...] */
    char tmp[RADE_TEXT_MAX_RAW + 1];
    memset(tmp, 0, sizeof(tmp));

    int maxChars = (strlength < RADE_TEXT_MAX_LENGTH) ? strlength : RADE_TEXT_MAX_LENGTH;
    callsign_to_ota(str, &tmp[RADE_TEXT_CRC_LENGTH], maxChars);

    int txtLen = (int)strlen(&tmp[RADE_TEXT_CRC_LENGTH]);
    if (txtLen > RADE_TEXT_MAX_LENGTH) txtLen = RADE_TEXT_MAX_LENGTH;
    tmp[0] = (char)crc8(&tmp[RADE_TEXT_CRC_LENGTH], txtLen);

    /* Pack into 56 information bits */
    unsigned char ibits[LDPC_NDATA];
    unsigned char pbits[LDPC_NPARITY];
    memset(ibits, 0, LDPC_NDATA);
    memset(pbits, 0, LDPC_NPARITY);

    /* First 8 bits: CRC byte */
    for (int b = 0; b < 8; b++)
        if (tmp[0] & (1 << b)) ibits[b] = 1;

    /* Remaining 48 bits: 8 × 6-bit characters */
    for (int b = 8; b < LDPC_NDATA; b++) {
        int fromCrc = b - 8;
        unsigned char byte = (unsigned char)tmp[RADE_TEXT_CRC_LENGTH + fromCrc / 6];
        if (byte & (1 << (fromCrc % 6)))
            ibits[b] = 1;
    }

    /* LDPC encode */
    ldpc_encode(ibits, pbits);

    /* Combine info + parity, then interleave */
    char tmpbits[LDPC_CODELENGTH];
    memcpy(&tmpbits[0], ibits, LDPC_NDATA);
    memcpy(&tmpbits[LDPC_NDATA], pbits, LDPC_NPARITY);

    gp_interleave_bits(impl->tx_text, tmpbits);

    /* Map to QPSK symbols (I,Q float pairs) */
    for (int i = 0; i < GP_N; i++) {
        char b0 = impl->tx_text[2 * i];
        char b1 = impl->tx_text[2 * i + 1];
        /* Same mapping as freedv-gui / codec2:
           00 → (+1, 0), 01 → (0, +1), 10 → (0, -1), 11 → (-1, 0) */
        if      (b0 == 0 && b1 == 0) { syms[2*i] =  1; syms[2*i+1] =  0; }
        else if (b0 == 0 && b1 == 1) { syms[2*i] =  0; syms[2*i+1] =  1; }
        else if (b0 == 1 && b1 == 0) { syms[2*i] =  0; syms[2*i+1] = -1; }
        else                          { syms[2*i] = -1; syms[2*i+1] =  0; }
    }

    /* Pad remaining symbols with known sequence */
    for (int i = LDPC_CODELENGTH; i < symSize; i++)
        syms[i] = (i % 2) ? 0.0f : 1.0f;
}

void rade_text_rx(rade_text_t ptr, float *syms, int symSize) {
    rade_text_impl_t *impl = (rade_text_impl_t *)ptr;
    int nsyms = LDPC_CODELENGTH / 2;   /* 56 QPSK symbols */

    /* Deinterleave received QPSK symbols */
    rt_comp deinterleaved[GP_N];
    gp_deinterleave_comp(deinterleaved, (rt_comp *)syms);

    /* Calculate RMS amplitude */
    float rms = 0.0f;
    for (int i = 0; i < nsyms; i++)
        rms += deinterleaved[i].real * deinterleaved[i].real
             + deinterleaved[i].imag * deinterleaved[i].imag;
    /* Include unused symbols in RMS denominator for consistency with freedv-gui */
    int totalSyms = symSize / 2;
    for (int i = nsyms; i < totalSyms; i++) {
        float sr = syms[2 * i], si = syms[2 * i + 1];
        rms += sr * sr + si * si;
    }
    rms = sqrtf(rms / (totalSyms > 0 ? totalSyms : 1));

    /* Build amplitude array (uniform = RMS) */
    float amps[GP_N];
    for (int i = 0; i < nsyms; i++) amps[i] = rms;

    /* Convert symbols to LLRs */
    float llr[LDPC_CODELENGTH];
    float EsNo = 3.0f;  /* constant from freedv_700.c */
    symbols_to_llrs(llr, deinterleaved, amps, EsNo, rms, nsyms);

    /* LDPC decode */
    uint8_t output[LDPC_CODELENGTH];
    int parityCheckCount = 0;
    ldpc_decode(output, llr, &parityCheckCount);

    /* Check BER estimate */
    float ber_est = (float)(LDPC_NPARITY - parityCheckCount) / LDPC_NPARITY;
    if (ber_est >= 0.2f) return;  /* too many errors */

    /* Extract raw bytes from decoded bits */
    char rawStr[RADE_TEXT_MAX_RAW + 1];
    memset(rawStr, 0, sizeof(rawStr));

    /* First 8 bits → CRC byte */
    for (int b = 0; b < 8; b++)
        if (output[b]) rawStr[0] |= (1 << b);

    /* Remaining bits → 6-bit OTA characters */
    for (int b = 8; b < LDPC_NDATA; b++) {
        int fromCrc = b - 8;
        if (output[b])
            rawStr[RADE_TEXT_CRC_LENGTH + fromCrc / 6] |= (1 << (fromCrc % 6));
    }

    /* Convert OTA to ASCII */
    char decoded[RADE_TEXT_MAX_RAW + 1];
    memset(decoded, 0, sizeof(decoded));
    decoded[0] = rawStr[0];  /* CRC */
    ota_to_callsign(&rawStr[RADE_TEXT_CRC_LENGTH], &decoded[RADE_TEXT_CRC_LENGTH],
                    RADE_TEXT_MAX_LENGTH);

    /* Verify CRC */
    unsigned char rxCRC  = (unsigned char)decoded[0];
    unsigned char calcCRC = crc8(&rawStr[RADE_TEXT_CRC_LENGTH], RADE_TEXT_MAX_LENGTH);

    if (rxCRC == calcCRC && impl->text_rx_callback) {
        const char *txt = &decoded[RADE_TEXT_CRC_LENGTH];
        impl->text_rx_callback(ptr, txt, (int)strlen(txt), impl->callback_state);
    }
}
